config/routes.rb
Rails.application.routes.draw do
  

  resources :categories

  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/about'

  get 'pages/contact'

  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'listings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
		has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
	else
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg",
					  :storage => :dropbox,
				      :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
				      :path => ":style/id_:filename"
	end
	validates_attachment_content_type :image, content_type: %w(image/jpeg image/jpg image/png image/gif)
	validates :name, :description, :price, presence: true
	validates :price, numericality: { greater_than_or_equal_to: 0 }

	geocoded_by :address               # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates

	belongs_to :user
	belongs_to :category
	has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :address, :city, :state, presence: true

  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    if params[:category].blank?
      @listings = Listing.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @listings = Listing.where(category_id: @category_id).order("created_at DESC")
    end
    @hash = Gmaps4rails.build_markers(@listings) do |listing, marker|
      marker.lat listing.latitude
      marker.lng listing.longitude
      marker.infowindow listing.name
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :category_id, :description, :price, :image, :address, :longitude, :latitude)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Oh EventMy!, you are not the admin for this event"
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

   def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
    respond_with(@order)
  end

  def create
    @order = Order.new(order_params)
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
<p>Copyright EventMy 2014</p>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">EventMy beta</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Explorasi<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, listings_path(category: category.name) %></li>
              <% end %>
            </ul>
          </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Manage Listings", seller_path %></li>
              <li><%= link_to "Sales History", sales_path %></li>
              <li><%= link_to "Purchase History", purchases_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <li><%= link_to "Create Event", new_listing_path, class: "btn btn-danger btn-sm" %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventmyDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>
  <%= yield %>

  <%= render 'layouts/footer' %>


</body>
</html>

app/views/listings/_form.html.erb
  <%= form_for(@listing, :html => { :multipart => true }) do |f| %>
    <% if @listing.errors.any? %>
      <div id="error_explanation" class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

        <ul>
        <% @listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<form class="form-inline" role="form">
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :category_id %><br>
          <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a category"}, {class: "btn btn-default dropdown-toggle"} %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %><br>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image %><br>
          <%= f.file_field :image, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: "form-control" %>
        </div>   
       
        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
        </div>
  </form>
  <% end %>

app/views/listings/edit.html.erb
<div class="container">
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div> 

app/views/listings/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div class="listing">
  <div class="jumbotron">
    <div class="container">
      <h1>Malaysian Event Marketplace</h1>
          <p>Whether you're organizing a seminar, fundraising dinner, academic exhibition or <br>business conference, EventMy provides the online tools you need</p>
          <br>
          <%= link_to new_user_registration_path, class: "btn btn-primary btn-lg" do %>
            <i class="glyphicon glyphicon-hdd"></i>Sign Up Today<% end %>
          
          <a class="btn btn-primary btn-lg" href="#" role="button">Explore Events &raquo;</a>
     
    </div>
  </div>

  <div class="container">
    <div class="center">
      <h2>Explore your mission locally</h2><hr>
      <div class="row">
        <% @listings.each do |listing| %>
          <div class="col-md-3">
             <div class="thumbnail">
              <%= link_to image_tag(listing.image.url), listing %>
               <div class="caption">
                 <h3><%= listing.name %></h3>
                 <p><strong><%= number_to_currency(listing.price, unit: "RM") %></strong></p>
                 <p><%= "By #{listing.user.name}" %></p>
               </div>
             </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<br>
    <div style='width: 100%;'>
      <div id="map" style='width: 100%; height: 400px;'></div>
    </div>

<script type="text/javascript">
 handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

</div>

app/views/listings/new.html.erb
<div class="container">
	<h1>New listing</h1>

	<%= render 'form' %>

	<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/listings/seller.html.erb
<div class="seller">
    <div class="jumbotron">
      <div class="container">
        <h1>Manage Listing</h1>
      </div>
    </div>
</div>
<div class="seller_table">
  <div class="container">
    <table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

      <% @listings.each do |listing| %>
        <tr>
          <td><%= image_tag listing.image.url(:thumb) %></td>
          <td><%= listing.name %></td>
          <td><%= listing.description %></td>
          <td><%= number_to_currency(listing.price) %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Action <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "View", listing %></li>
                <li><%= link_to "Edit", edit_listing_path(listing) %></li>
                <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" } %></li>
              </ul>
            </div>
           </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/listings/show.html.erb
<div class="listing_show">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="thumbnail">
					<%= image_tag @listing.image.url %>
				</div>
			</div>
			<div class="col-md-6">
				<h3><%= @listing.name %></h3>
				<p><%= number_to_currency(@listing.price) %></p>
				<p><%= @listing.description %></p>
				<p><%= @listing.address %></p>
				<br>
			    <div class="center">
			      <%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary" %>
			   
			    </div>
			</div>
		</div>

 

			<% if current_user == @listing.user %>
			<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
		<% end %>
		<%= link_to 'Back', listings_path, class: "btn btn-link" %>
	</div>
</div>

app/views/orders/_form.html.erb
<%= form_for([@listing, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Complete Order", class: "btn btn-success" %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="seller">
    <div class="jumbotron">
      <div class="container">
        <h1>Purchase History</h1>
      </div>
    </div>
</div>
<div class="seller_table">
  <div class="container">
    <table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Organizer</th>
    <th class="center">Date Purchase</th>
  </tr>

      <% @orders.each do |order| %>
        <tr>
          <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
          <td class="center"><%= order.listing.name %></td>
          <td class="center"><%= number_to_currency(order.listing.price) %></td>
          <td class="center"><%= order.seller.name %></td>
          <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/orders/sales.html.erb
<div class="seller">
    <div class="jumbotron">
      <div class="container">
        <h1>Sales History</h1>
      </div>
    </div>
</div>
<div class="seller_table">
  <div class="container">
    <table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>

      <% @orders.each do |order| %>
        <tr>
          <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
          <td class="center"><%= order.listing.name %></td>
          <td class="center"><%= number_to_currency(order.listing.price) %></td>
          <td class="center"><%= order.buyer.name %></td>
          <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/pages/about.html.erb
<div class="about">
	<div class="jumbotron">
		<div class="container">
			<h1>Welcome to EventMy</h1>
			<h2>The Malaysian online event marketplace</h2>
			<p>Created by 'Megat Taufiq'</p>
		</div>
</div>
</div>

app/views/pages/contact.html.erb
<h1>Email us at EventMy_demo@eventmy.com</h1>